// generated by stringer -type=Token; DO NOT EDIT

package lang

import "fmt"

const _Token_name = "IllegalEOFWhitespaceIdentifierQuotesOpenParenCloseParenAssignString"

var _Token_index = [...]uint8{0, 7, 10, 20, 30, 36, 45, 55, 61, 67}

func (i Token) String() string {
	i -= 1
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i+1)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
